version: "3.8"

services:
  localstack:
    container_name: "localstack_observabilidade"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # External services
    environment:
      - DEBUG=0
      - SERVICES=eks,s3,iam
      - EKS_K3S_VERSION=v1.28.3-k3s1
      - DEFAULT_REGION=us-east-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
